### PR TITLE
Local storage disabled bugfixes. 

### LINKED ISSUE #457: messy UX in new version
Is it possible to return old interface instead of the new messy one? This is a definite step down in the terms of UX.

PS: And why the hell two scrollbars??

### LINKED ISSUE #458: UI broken
Hi,
Since an update today of PB the UI is broken in FireFox 39 / Windows 7.

pberror

None of the UI buttons in the dialogue box work. I have disabled all other extensions in FireFox. 

The status (just below the two badger heads) says "Loading..."

Regards,

Bernt

### LINKED ISSUE #464: Extraneous scrollbar in UI on Firefox on Linux
In Firefox Badger's UI is being broken with a vertical scrollbar in an area that looks like it should never gain any scrollbars:

badger_misaligned

This is causing the weird and sloppy scrolling behaviour seen on this screenshot.

I suspect some elements turn out to be higher (fonts?) for this combination of browser and OS than in other environments, triggering the browser to render a scrollbar for the taller-than-expected pane.

* Firefox 39.0
* Ubuntu Linux 14.10 (Unity)
* Privacy Badger 1.0.0

### PR DESCRIPTION
**Pull request by cooperq**
Fixes #457 
Fixes #458 
Fixes #464 

The popup was trying to access a flag in localStorage which was causing myriad problems for users that had localStorage turned off. This patch set fixes all of those problems. 

cc @jsha for review.

### CODE REVIEW

File: lib/ui.js [hunk 1]
```diff
@@ -394,9 +398,23 @@ exports.clearSettingsMap = function(aWin) {
 };
 
 /**
+ * Handle firstrun page
+ */
+pageMod.PageMod({
+  include: data.url("firstRun.html*"),
```
Comment (jsha) [inline lib/ui.js]: The `*` here seems spurious.

Comment (cooperq) [inline lib/ui.js]: Nope! It covers the case where there is an anchor tag after the resource, such as firstRun.html#slideshow

Otherwise the script doesn't load when you click the link in the popup.

File: lib/userStorage.js [hunk 2]
```diff
@@ -378,6 +387,14 @@ exports.isDomainException = function(url, trackingHost, context) {
   }, context);
 };
 
+exports.setSeenComic = function(setting){
+  storage['seenComic'] = setting;
+}
+
+exports.getSeenComic = function(setting){
+  return storage['seenComic'] || false;
```
Comment (jsha) [inline lib/userStorage.js]: Another JS idiom, if you like it, is `!!storage['seenComic']`.

File: lib/ui.js (hunk 1 above)
Comment (jsha) [inline lib/ui.js]: Weird! That deserves a comment, I think.

**Comment by jsha** [comment]
LGTM! Go ahead and merge after adding a comment.

**Comment by jsha** [comment]
LGTM
